# Generated by Django 3.0.3 on 2020-02-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='eamil',
            new_name='email',
        ),
    ]
