version: "3.7"

services:
  web:
    build: .
    command: python /kids_python/manage.py runserver 0.0.0.0:8000
    # command: gunicorn project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
      - SECRET_KEY=4=^(lq704azdxugn)&5_o(=dj2*_%ckx5llt-)_27qvaf3kiv8
    volumes:
      - .:/kids_python
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
