version: '3.7'

services: 
    web:
        build: .
        command: python /kids_python/manage.py runserver 0.0.0.0:8000
        # command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
        environment: 
            - DEBUG=1
        volumes:
            - .:/kids_python
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data: